CREATE TABLE postal_offices (
   postal_index BIGINT PRIMARY KEY NOT NULL,
   name VARCHAR(255),
   address VARCHAR(255)
);
CREATE TABLE receivers (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   address VARCHAR(255),
   postal_office_id BIGINT NOT NULL,
   CONSTRAINT pk_receivers PRIMARY KEY (id),
   FOREIGN KEY (postal_office_id) REFERENCES postal_offices (postal_index),
   CONSTRAINT UC_RECEIVER UNIQUE(name, address)
);
CREATE TABLE mailings (
   mailing_id BIGINT NOT NULL PRIMARY KEY,
   type VARCHAR(255),
   receiver_id BIGINT,
   status VARCHAR(255) NOT NULL,
   FOREIGN KEY (receiver_id) REFERENCES receivers (id)
);
CREATE TABLE mailing_movements (
   movement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   mailing_id BIGINT,
   postal_office_id BIGINT,
   arrival_date_time TIMESTAMP WITHOUT TIME ZONE,
   departure_date_time TIMESTAMP WITHOUT TIME ZONE,
   FOREIGN KEY (mailing_id) REFERENCES mailings (mailing_id),
   FOREIGN KEY (postal_office_id) REFERENCES postal_offices (postal_index)
);
